name: powapong
version: 1.0.0+1
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  audioplayers: ^5.2.0
  rive: ^0.12.4
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  qr_code_scanner: ^1.0.1
  http: ^1.2.1
  flutter_svg: ^2.0.10
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/sounds/
    - lib/assets/icons/
